runtime: python27
api_version: 1
threadsafe: yes

automatic_scaling:
  max_file_size: 100M

handlers:
  - url: /
    static_files: dist/my-app/index.html
    upload: dist/my-app/index.html
  - url: /
    static_dir: dist/my-app

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
